name: Federer_verification

on:
  pull_request:
    branches: [ main, functions_devel ]
  push:
    branches: [ main, functions_devel ]

jobs:
  build_ws:
    runs-on: ubuntu-20.04
    steps:
      - uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: foxy
      - run: vcs --help