name: Federer verification
on:
  pull_request:
    branches: [ main, devel ]
  push:
    branches: [ main, devel ]
jobs:
  install_os:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@v0.5
      with:
        required-ros-distributions: foxy
      - run: vcs --help
