name: Federer_verification
on:
  pull_request:
    branches: [ main, devel ]
  push:
    branches: [ main, devel ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.5
      with:
        required-ros-distributions: foxy
      - run: vcs --help